pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone --bare git@bitbucket.org:lokee-vj/azure-functions-docker-python-sample.git
          - cd azure-functions-docker-python-sample.git
          - git push git@github.com:lokee-vj/azure-functions-docker-python-sample.git dev